groups:
  - name: app_alerts
    rules:
      - alert: HighRequestLatency
        expr: http_request_duration_seconds{quantile="0.9"} > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a 90th percentile latency of {{ $value }} seconds for the past 5 minutes."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a high HTTP error rate: {{ $value | humanizePercentage }}."

      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighCPULoad
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU load on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a CPU load above 80% for the past 5 minutes."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has memory usage above 85% for the past 5 minutes."

  - name: rabbitmq_alerts
    rules:
      - alert: RabbitMQDown
        expr: rabbitmq_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "RabbitMQ is down"
          description: "RabbitMQ instance is down for more than 1 minute."

      - alert: RabbitMQHighMemoryUsage
        expr: rabbitmq_node_mem_used / rabbitmq_node_mem_limit > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "RabbitMQ high memory usage"
          description: "RabbitMQ memory usage is above 80% for more than 5 minutes."

      - alert: RabbitMQTooManyUnacknowledgedMessages
        expr: sum(rabbitmq_queue_messages_unacknowledged) by (queue) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many unacknowledged messages in {{ $labels.queue }}"
          description: "Queue {{ $labels.queue }} has more than 1000 unacknowledged messages for more than 5 minutes."

      - alert: RabbitMQNodeNotRunning
        expr: rabbitmq_running == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "RabbitMQ node not running"
          description: "RabbitMQ node is not running for more than 1 minute."
